# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import scraper_pb2 as scraper__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scraper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScraperServiceStub(object):
    """ScraperService handles content extraction from various platforms
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScrapeContent = channel.unary_unary(
                '/scraper.ScraperService/ScrapeContent',
                request_serializer=scraper__pb2.ScrapeRequest.SerializeToString,
                response_deserializer=scraper__pb2.ScrapeResponse.FromString,
                _registered_method=True)


class ScraperServiceServicer(object):
    """ScraperService handles content extraction from various platforms
    """

    def ScrapeContent(self, request, context):
        """ScrapeContent extracts content (captions, transcript) from a URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScrapeContent': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeContent,
                    request_deserializer=scraper__pb2.ScrapeRequest.FromString,
                    response_serializer=scraper__pb2.ScrapeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scraper.ScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scraper.ScraperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScraperService(object):
    """ScraperService handles content extraction from various platforms
    """

    @staticmethod
    def ScrapeContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/ScrapeContent',
            scraper__pb2.ScrapeRequest.SerializeToString,
            scraper__pb2.ScrapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
