# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scraper.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scraper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscraper.proto\x12\x07scraper\"m\n\rScrapeRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12#\n\x08platform\x18\x02 \x01(\x0e\x32\x11.scraper.Platform\x12\x16\n\x0e\x64ownload_video\x18\x03 \x01(\x08\x12\x12\n\ntranscribe\x18\x04 \x01(\x08\"\xd5\x01\n\x0eScrapeResponse\x12\x10\n\x08\x63\x61ptions\x18\x01 \x01(\t\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x14\n\x0coriginal_url\x18\x03 \x01(\t\x12\x37\n\x08metadata\x18\x04 \x03(\x0b\x32%.scraper.ScrapeResponse.MetadataEntry\x12\x1d\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x0e.scraper.Error\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t*u\n\x08Platform\x12\x14\n\x10PLATFORM_UNKNOWN\x10\x00\x12\x13\n\x0fPLATFORM_TIKTOK\x10\x01\x12\x14\n\x10PLATFORM_YOUTUBE\x10\x02\x12\x16\n\x12PLATFORM_INSTAGRAM\x10\x03\x12\x10\n\x0cPLATFORM_WEB\x10\x04\x32R\n\x0eScraperService\x12@\n\rScrapeContent\x12\x16.scraper.ScrapeRequest\x1a\x17.scraper.ScrapeResponseB)Z\'receipt-bot/internal/adapters/python/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scraper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'receipt-bot/internal/adapters/python/pb'
  _globals['_SCRAPERESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_SCRAPERESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PLATFORM']._serialized_start=393
  _globals['_PLATFORM']._serialized_end=510
  _globals['_SCRAPEREQUEST']._serialized_start=26
  _globals['_SCRAPEREQUEST']._serialized_end=135
  _globals['_SCRAPERESPONSE']._serialized_start=138
  _globals['_SCRAPERESPONSE']._serialized_end=351
  _globals['_SCRAPERESPONSE_METADATAENTRY']._serialized_start=304
  _globals['_SCRAPERESPONSE_METADATAENTRY']._serialized_end=351
  _globals['_ERROR']._serialized_start=353
  _globals['_ERROR']._serialized_end=391
  _globals['_SCRAPERSERVICE']._serialized_start=512
  _globals['_SCRAPERSERVICE']._serialized_end=594
# @@protoc_insertion_point(module_scope)
