// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: scraper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Platform represents supported content platforms
type Platform int32

const (
	Platform_PLATFORM_UNKNOWN   Platform = 0
	Platform_PLATFORM_TIKTOK    Platform = 1
	Platform_PLATFORM_YOUTUBE   Platform = 2
	Platform_PLATFORM_INSTAGRAM Platform = 3
	Platform_PLATFORM_WEB       Platform = 4
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNKNOWN",
		1: "PLATFORM_TIKTOK",
		2: "PLATFORM_YOUTUBE",
		3: "PLATFORM_INSTAGRAM",
		4: "PLATFORM_WEB",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNKNOWN":   0,
		"PLATFORM_TIKTOK":    1,
		"PLATFORM_YOUTUBE":   2,
		"PLATFORM_INSTAGRAM": 3,
		"PLATFORM_WEB":       4,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_scraper_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_scraper_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

// ScrapeRequest contains the URL and platform to scrape
type ScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Platform      Platform               `protobuf:"varint,2,opt,name=platform,proto3,enum=scraper.Platform" json:"platform,omitempty"`
	DownloadVideo bool                   `protobuf:"varint,3,opt,name=download_video,json=downloadVideo,proto3" json:"download_video,omitempty"` // Whether to download video for transcription
	Transcribe    bool                   `protobuf:"varint,4,opt,name=transcribe,proto3" json:"transcribe,omitempty"`                            // Whether to transcribe audio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	mi := &file_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScrapeRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNKNOWN
}

func (x *ScrapeRequest) GetDownloadVideo() bool {
	if x != nil {
		return x.DownloadVideo
	}
	return false
}

func (x *ScrapeRequest) GetTranscribe() bool {
	if x != nil {
		return x.Transcribe
	}
	return false
}

// ScrapeResponse contains extracted content
type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Captions      string                 `protobuf:"bytes,1,opt,name=captions,proto3" json:"captions,omitempty"`                                                                           // Video captions/description
	Transcript    string                 `protobuf:"bytes,2,opt,name=transcript,proto3" json:"transcript,omitempty"`                                                                       // Video transcript from audio
	OriginalUrl   string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`                                                  // Original video URL
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata (author, title, etc.)
	Error         *Error                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error if scraping failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResponse) GetCaptions() string {
	if x != nil {
		return x.Captions
	}
	return ""
}

func (x *ScrapeResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *ScrapeResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ScrapeResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ScrapeResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Error represents an error that occurred during scraping
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_scraper_proto protoreflect.FileDescriptor

const file_scraper_proto_rawDesc = "" +
	"\n" +
	"\rscraper.proto\x12\ascraper\"\x97\x01\n" +
	"\rScrapeRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12-\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x11.scraper.PlatformR\bplatform\x12%\n" +
	"\x0edownload_video\x18\x03 \x01(\bR\rdownloadVideo\x12\x1e\n" +
	"\n" +
	"transcribe\x18\x04 \x01(\bR\n" +
	"transcribe\"\x95\x02\n" +
	"\x0eScrapeResponse\x12\x1a\n" +
	"\bcaptions\x18\x01 \x01(\tR\bcaptions\x12\x1e\n" +
	"\n" +
	"transcript\x18\x02 \x01(\tR\n" +
	"transcript\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.scraper.ScrapeResponse.MetadataEntryR\bmetadata\x12$\n" +
	"\x05error\x18\x05 \x01(\v2\x0e.scraper.ErrorR\x05error\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code*u\n" +
	"\bPlatform\x12\x14\n" +
	"\x10PLATFORM_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPLATFORM_TIKTOK\x10\x01\x12\x14\n" +
	"\x10PLATFORM_YOUTUBE\x10\x02\x12\x16\n" +
	"\x12PLATFORM_INSTAGRAM\x10\x03\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x042R\n" +
	"\x0eScraperService\x12@\n" +
	"\rScrapeContent\x12\x16.scraper.ScrapeRequest\x1a\x17.scraper.ScrapeResponseB)Z'receipt-bot/internal/adapters/python/pbb\x06proto3"

var (
	file_scraper_proto_rawDescOnce sync.Once
	file_scraper_proto_rawDescData []byte
)

func file_scraper_proto_rawDescGZIP() []byte {
	file_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)))
	})
	return file_scraper_proto_rawDescData
}

var file_scraper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scraper_proto_goTypes = []any{
	(Platform)(0),          // 0: scraper.Platform
	(*ScrapeRequest)(nil),  // 1: scraper.ScrapeRequest
	(*ScrapeResponse)(nil), // 2: scraper.ScrapeResponse
	(*Error)(nil),          // 3: scraper.Error
	nil,                    // 4: scraper.ScrapeResponse.MetadataEntry
}
var file_scraper_proto_depIdxs = []int32{
	0, // 0: scraper.ScrapeRequest.platform:type_name -> scraper.Platform
	4, // 1: scraper.ScrapeResponse.metadata:type_name -> scraper.ScrapeResponse.MetadataEntry
	3, // 2: scraper.ScrapeResponse.error:type_name -> scraper.Error
	1, // 3: scraper.ScraperService.ScrapeContent:input_type -> scraper.ScrapeRequest
	2, // 4: scraper.ScraperService.ScrapeContent:output_type -> scraper.ScrapeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_scraper_proto_init() }
func file_scraper_proto_init() {
	if File_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_proto_depIdxs,
		EnumInfos:         file_scraper_proto_enumTypes,
		MessageInfos:      file_scraper_proto_msgTypes,
	}.Build()
	File_scraper_proto = out.File
	file_scraper_proto_goTypes = nil
	file_scraper_proto_depIdxs = nil
}
